# Generated by Django 5.0.2 on 2024-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book66", "0004_author_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="orders",
            field=models.ManyToManyField(related_name="buyer", to="book66.order"),
        ),
    ]
