# Generated by Django 5.0.2 on 2024-03-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book66", "0006_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
